-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=`TRADITIONAL,ALLOW_INVALID_DATES`;


-- -----------------------------------------------------
-- Schema ukp
-- -----------------------------------------------------

# Drop SCHEMA dbo;
CREATE SCHEMA IF NOT EXISTS `dbo` DEFAULT CHARACTER SET utf8 ;
USE `dbo` ;



-- -----------------------------------------------------
-- Table `dbo`.`routine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbo`.`routine` ;

CREATE TABLE IF NOT EXISTS  `dbo`.`routine` (
	`id_origin` int NOT NULL AUTO_INCREMENT,
	`id` int NOT NULL , -- ID-  ид–точки 10 штук
	`dayofweek` smallint NULL, -- ссылка на таблицу pn_daynames
	`workfrom` datetime NULL, -- режим работы с
	`workto` datetime NULL, -- режим работы по
	`intervalfrom` datetime NULL, -- перерыв с
	`intervalto` datetime NULL, -- перерыв по
	PRIMARY KEY (`id_origin`),
	CONSTRAINT `fk_pn_daynamesId`
	FOREIGN KEY (`dayofweek`)
	REFERENCES `dbo`.`pn_daynames` (`id`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION)
	ENGINE = InnoDB
	DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`pn_daynames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbo`.`pn_daynames` ;

CREATE TABLE IF NOT EXISTS `dbo`.`pn_daynames`(
`id` smallint NOT NULL ,  --
`name` varchar(50) NULL, -- название дня
`countday` int NULL, -- колличество дней в даной строке.
`orderby` int NULL, -- параметр для того, что б правильно упорядочить
`short_name` varchar(10) NULL, -- короткое название имени
`days` varchar(50) NULL, -- ссылка на день недели 1-7
PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

